name: Build and Push to Zot
on:
  push:
    branches: [main, master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
          buildkitd-config-inline: |
            [registry."registry-taloslab.subetupaginacp.com"]
              http = true
              insecure = true
      - name: Log in to Local Zot Registry
        run: |
          echo "${{ secrets.ZOT_PASSWORD }}" | docker login registry-taloslab.subetupaginacp.com:5000 --username cleanup --password-stdin
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: registry-taloslab.subetupaginacp.com:5000/palbina/portfolio-astro:latest
